<?xml version = "1.0"?>
<?translator version="1.0" ?>

<!DOCTYPE language
[
	<!ELEMENT language ( word+, (root*) )>
	<!ELEMENT word ( definition+, translation* ) >
	<!ATTLIST language name CDATA #REQUIRED >
	<!ELEMENT definition ( (part_of_speech), (description) ) >
	<!ATTLIST part_of_speech part CDATA #REQUIRED >
	<!ELEMENT description ( #PCDATA ) >
	<!ATTLIST translation language CDATA #REQUIRED>
	<!ATTLIST translation word CDATA #REQUIRED>
	<!ATTLIST root name CDATA #REQUIRED>
	<!ATTLIST root type CDATA #REQUIRED>
	<!ATTLIST root definition CDATA #REQUIRED>
]
>

<language name = "Ancient Language">

	<word name = "lac">
		<definition>
			<part_of_speech
				part="@parts_of_speech/noun"/>
			<description>This fluid appearing in or flowing from the eye as the result of emotion, especially grief</description>
		</definition>
		
		<definition>
			<part_of_speech
				part="@parts_of_speech/noun"/>
			<description>A rent or fissure.</description>
		</definition>
		
		<definition>
			<part_of_speech
				part="@parts_of_speech/verb"/>
			<description>To become torn.</description>
		</definition>
		
		<translation
			language="English"
			word="tear"/>
		
		<translation
			language="English"
			word="fissure"/>
	</word>

	<word name = "vjis">
		<definition>
			<part_of_speech
				part="@parts_of_speech/noun"/>
			<description>The solid form of water;verb to cover with ice.</description>
		</definition>
		
		<translation
			language="English"
			word="ice"/>
	</word>
	
	<root
		name="a, an"
		type="@root_types/prefix"
		definition="without, not"
		/>
		
</language>














